![Itq](img/logoitqv1.jpg)

**MIAR - Estructuras de datos, +Pandas**

![Python](img/python_logo.png)

* *Nombre:* Judith Piedra
* *Fecha :* **07-07-2026**
* *Repositorio:* <a href= "https://github.com/MerakiDevJP/machine1_23062026nocturno.git"> Link del repositorio Github</a>
* https://github.com/MerakiDevJP/machine1_23062026nocturno.git

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.3'

# Operaciones en pandas
**Búsqueda**

In [3]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  5  2  0
1  5  2  1

In [4]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [5]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

       A     B      C
0  False  True  False
1  False  True  False

In [6]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

0

       A      B      C
0  False  False  False
1  False  False  False

[[False False False]
 [False False False]]

numpy.ndarray

In [7]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

4

      A     B      C
0  True  True  False
1  True  True  False

**Ordenación**

In [8]:
from random import shuffle

rand_matrix = np.random.randint(20,size=(5,4))

indices = list(range(5))
shuffle(indices) # mezcla indices

frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D   A   C   B
2  19  17  19  19
0   9  10   2  12
3   8   7  15   7
1  14   5   2  17
4   8   6   2  19

In [9]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4   8   6   2  19
3   8   7  15   7
2  19  17  19  19
1  14   5   2  17
0   9  10   2  12

    D   A   C   B
2  19  17  19  19
0   9  10   2  12
3   8   7  15   7
1  14   5   2  17
4   8   6   2  19

In [10]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
2  19  19  19  17
0   9   2  12  10
3   8  15   7   7
1  14   2  17   5
4   8   2  19   6

In [11]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
1  14   5   2  17
4   8   6   2  19
3   8   7  15   7
0   9  10   2  12
2  19  17  19  19

In [12]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    C   A   D   B
2  19  17  19  19
0   2  10   9  12
3  15   7   8   7
1   2   5  14  17
4   2   6   8  19

In [13]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
2  19  17  19  19
0   9  10   2  12
3   8   7  15   7
4   8   6   2  19
1  14   5   2  17

**Ranking**
- Construir un ranking de valores

In [14]:
display(frame)

    D   A   C   B
2  19  17  19  19
0   9  10   2  12
3   8   7  15   7
4   8   6   2  19
1  14   5   2  17

In [15]:
display(frame.rank(method='max', axis=1))

     D    A    C    B
2  4.0  1.0  4.0  4.0
0  2.0  3.0  1.0  4.0
3  3.0  2.0  4.0  2.0
4  3.0  2.0  1.0  4.0
1  3.0  2.0  1.0  4.0

In [17]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

19
15
2
2
2

# Operaciones
- Operaciones matemáticas entre objetos

In [18]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  51  71  86  59
1  42  28  22  18
2  69  30   4  28
3  73  70   3  89

    0   1   2   3
0   7   8  93   7
1  38   4  77  26
2  94  42  97   7
3  51  88  75  51

In [19]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2    3
0   58   79  179   66
1   80   32   99   44
2  163   72  101   35
3  124  158   78  140

In [20]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0 -44 -63   7 -52
1  -4 -24  55   8
2  25  12  93 -21
3 -22  18  72 -38

In [21]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  51  71  86  59
1  42  28  22  18
2  69  30   4  28
3  73  70   3  89

    0   1   2
0  58  33  70
1  52  61  92
2  63  49  71

       0      1      2   3
0  109.0  104.0  156.0 NaN
1   94.0   89.0  114.0 NaN
2  132.0   79.0   75.0 NaN
3    NaN    NaN    NaN NaN

In [22]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1      2     3
0  109.0  104.0  156.0  59.0
1   94.0   89.0  114.0  18.0
2  132.0   79.0   75.0  28.0
3   73.0   70.0    3.0  89.0

- Operadores aritméticos solo válidos en elementos aceptables

In [25]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
try:
    # Se realiza la operación aritmética
    resultado = frameA - frameD
    display(resultado)
except TypeError:
    # Si detecta que no se pueden restar (ej. texto - números), lanza tu error personalizado
    print("Error: No se puede realizar la operación aritmética porque uno de los DataFrames contiene datos no numéricos.")
except Exception as e:
    # Captura cualquier otro error inesperado
    print(f"Ocurrió un error inesperado: {e}")

   0  1
0  a  d
1  b  f

Error: No se puede realizar la operación aritmética porque uno de los DataFrames contiene datos no numéricos.

- Operaciones entre Series y DataFrames

In [26]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)

display(df.iloc[0])
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  0  4  5  3
1  6  2  4  8
2  0  0  9  1

A    0
B    4
C    5
D    3
Name: 0, dtype: int32

pandas.Series

   A  B  C  D
0  0  0  0  0
1  6 -2 -1  5
2  0 -4  4 -2

   A  B  C  D
0  0  0  0  0
1  6 -2 -1  5
2  0 -4  4 -2

   A  B  C  D
0  0  4  5  3
1  0 -4 -2  2
2  0  0  9  1

- pandas se basa en NumPy, np operadores binarios y unarios son aceptables

### Operadores unarios y binarios
| Tipo | Operación | Descripción |
| :--- | :--- | :--- |
| **Unario** | `abs` | Valor absoluto de cada elemento |
| | `sqrt` | Raíz cuadrada de cada elemento |
| | `exp` | $e^x$, siendo $x$ cada elemento |
| | `log`, `log10`, `log2` | Logaritmos en distintas bases de cada elemento |
| | `sign` | Retorna el signo (-1 negativo, 0 o 1 positivo) |
| | `ceil` | Redondea cada elemento por arriba |
| | `floor` | Redondea cada elemento por abajo |
| | `isnan` | Retorna si cada elemento es NaN |
| | `cos`, `sin`, `tan` | Operaciones trigonométricas |
| | `arccos`, `arcsin`, `arctan` | Inversas de operaciones trigonométricas |
| **Binario** | `add` | Suma de dos arrays |
| | `substract` | Resta de dos arrays |
| | `multiply` | Multiplicación de dos arrays |
| | `divide` | División de dos arrays |
| | `maximum`, `minimum` | Retorna el valor máximo/mínimo de cada pareja |
| | `equal`, `not_equal` | Comparación de igualdad o desigualdad |
| | `greater`, `greater_equal`, `less`, `less_equal` | Comparaciones: $>$, $\ge$, $<$, $\le$ respectivamente |

- Aplicación de funciones a medida con lambda

In [27]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por columna

   A  B  C  D
0  1  9  2  0
1  1  8  1  4
2  1  1  2  5

0    9
1    7
2    4
dtype: int32

In [28]:
def max_min(x):
    return x.max() - x.min()

print(frame.apply(max_min, axis = 0)) # diferencia por columna

A    0
B    8
C    1
D    5
dtype: int32

In [29]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  3  3  0  0
1  6  5  6  8
2  7  2  1  6

0    3
1    3
2    6
dtype: int32

In [30]:
def max_min(x):
    return x.max() - x.min()

print(frame.apply(max_min, axis = 0)) # diferencia por columna

A    4
B    3
C    6
D    8
dtype: int32

In [31]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  7  3  5  9
1  6  6  4  7
2  8  7  9  5

0    6
1    3
2    4
dtype: int32

# Estadística descriptiva
- Análisis preliminar de los datos
- Para Series y DataFrame


|Operación|Descripción|
| :--- | :--- |
|count |Número de valores no NaN|
|describe |Conjunto de estadísticas sumarias|
|min, max |Valores mínimo y máximo|
|argmin, argmax |Índices posicionales del valor mínimo y máximo|
|idxmin, idxmax |Índices semánticos del valor mínimo y máximo|
|sum |Suma de los elementos|
|mean |Media de los elementos|
|median |Mediana de los elementos|
|mad |Desviación absoluta media del valor medio|
|var |Varianza de los elementos|
|std |Desviación estándar de los elementos|
|cumsum |Suma acumulada de los elementos|
|diff |Diferencia aritmética de los elementos|

In [32]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30],
                "puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [33]:
# operadores básicos
print(frame.sum())

display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [34]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [35]:
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [36]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [37]:
print(frame['edad'].std())

10.996211468804457

In [38]:
frame['edad'].idxmax()

0

In [39]:
frame['puntos'].idxmin()

1

In [40]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())

display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [43]:
frame["ranking"] = frame["puntos"].rank(method='max')
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

## Agregaciones

In [44]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [45]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [46]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [47]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [48]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [49]:
 # Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
    return x["edad"].mean() > 30
    
display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

## Correlaciones
- pandas incluye métodos para analizar correlaciones
- Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)
- obj.corr(obj2)
- medida de correlación entre los datos de ambos objetos
- https://blogs.oracle.com/ai-anddatascience/post/introduction-to-correlation

### Ejemplo Fuel efficiency
- https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [50]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
mpg_data = pd.read_csv(path, sep='\s+', header=None,
                       names = ['mpg', 'cilindros', 'desplazamiento','potencia',
                                'peso', 'aceleracion', 'año', 'origen', 'nombre'],
                        na_values='?', engine='c')

In [51]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
45,18.0,6,258.0,110.0,2962.0,13.5,71,1,amc hornet sportabout (sw)
352,29.9,4,98.0,65.0,2380.0,20.7,81,1,ford escort 2h
197,29.0,4,90.0,70.0,1937.0,14.2,76,2,vw rabbit
94,13.0,8,440.0,215.0,4735.0,11.0,73,1,chrysler new yorker brougham
146,28.0,4,90.0,75.0,2125.0,14.5,74,1,dodge colt

In [52]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [53]:
mpg_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    str
dtypes: float64(5), int64(3), str(1)
memory usage: 28.1 KB

### Correlaciones entre valores

In [54]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg = - peso

np.float64(-0.8317409332443352)

In [55]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso = - aceleracion

np.float64(-0.4174573199403932)

### Correlaciones entre todos los valores

In [56]:
 mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [75]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)
display(corr_data.style.background_gradient(cmap='RdYlGn', axis=1))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [73]:
 # representación gráfica matplotlib
import matplotlib.pyplot as plt
import matplotlib
print(matplotlib.__version__)

3.11.0

In [74]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [60]:
# correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: str

In [61]:
# correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax() #consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: str

In [81]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
# cálculo de la correlación
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).copy()
display(positive_corr)

np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
print(positive_corr.idxmax())

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: str

In [67]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
# cálculo de la correlación
positive_corr = mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True)

# 2. Modificamos la diagonal usando valores de relleno (sin convertir a numpy)
# Obtenemos los nombres de las columnas/índices
indices = positive_corr.columns

# Usamos fillna para asegurarnos de que no hay NaNs y luego asignamos 0 en la diagonal
for col in indices:
    positive_corr.loc[col, col] = 0
    
display(positive_corr)
positive_corr.idxmax()

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,0.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,0.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,0.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,0.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,0.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,0.000000

mpg                  aceleracion
cilindros         desplazamiento
desplazamiento         cilindros
potencia          desplazamiento
peso              desplazamiento
aceleracion                  mpg
dtype: str

## Ejercicios
- Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandaspuzzles/blob/master/100-pandas-puzzles.ipynb